import Foundation


class Database {
    static var Array : [MoviesObject] = []
   //static 3shan n2om bested3a2ha mobasharatan
    static func PutMovies() {
    let TheMartianAbout = """
The Martian is a 2015 science fiction film directed by Ridley Scott and starring Matt Damon. The screenplay by Drew Goddard is based on Andy Weir's 2011 novel of the same name about an astronaut who is mistakenly presumed dead and left behind on Mars. The film depicts his struggle to survive and others' efforts to rescue him. It also stars Jessica Chastain, Kristen Wiig, Jeff Daniels, Michael Peña, Kate Mara, Sean Bean, Sebastian Stan, Donald Glover, Aksel Hennie, and Chiwetel Ejiofor.

The film, produced through 20th Century Fox, is a co-production of the United States and the United Kingdom.[2] Producer Simon Kinberg began developing the film after Fox optioned the novel in March 2013, which Drew Goddard adapted into a screenplay and was initially attached to direct, but the film did not move forward. Scott replaced Goddard, and with Damon in place as the main character, production was approved. Filming began in November 2014 and lasted approximately seventy days. Twenty sets were built on a sound stage in Budapest, Hungary, one of the largest in the world. Wadi Rum in Jordan was also used as a backdrop for filming.

The film premiered at the 2015 Toronto International Film Festival on September 11, 2015, while the London premiere was held on September 24, 2015. The film was released in the United Kingdom on September 30, 2015 and in the United States on October 2, 2015 in 2D, 3D, IMAX 3D and 4DX.[5] It received positive reviews and grossed over $630 million worldwide, becoming Scott's highest-grossing film to date, as well as the 10th highest-grossing film of 2015. It received several accolades, including the Golden Globe Award for Best Motion Picture – Musical or Comedy, seven Academy Award nominations, including Best Picture and Best Adapted Screenplay for Goddard, and the 2016 long form Hugo Award for Best Dramatic Presentation. Damon won the Golden Globe Award for Best Actor – Motion Picture Musical or Comedy and was nominated for several awards including the Academy Award for Best Actor, the BAFTA Award for Best Actor in a Leading Role, and the Critic's Choice Award for Best Actor.

In 2035, the crew of the Ares III mission to Mars is exploring Acidalia Planitia on Martian solar day (sol) 18 of their 31-sol expedition. A strong dust storm threatens to topple their Mars Ascent Vehicle (MAV), forcing them to abort their mission. During the evacuation, astronaut Mark Watney is struck by debris and lost in the storm; the last telemetry from his suit indicates no signs of life. With Watney believed dead, the storm worsening by the second, and the MAV on the verge of toppling over, mission commander Melissa Lewis orders the crew to take off and return to their orbiting vessel, Hermes.

Watney awakens after the storm to a low oxygen warning and makes his way to the "Hab" (short for "habitat"), the crew's base of operations. He removes the piece of antenna that destroyed his suit's biomonitor and lodged in his torso by performing self-surgery. He begins a video diary and realizes that his only chance of rescue is to rendezvous with the Ares IV crew at the Schiaparelli crater, 3,200 kilometres (2,000 mi) away in four years. His immediate concern is there will not be enough food to survive that long. Watney, being a botanist, improvises a farm inside the Hab utilizing Martian soil fertilized with human waste, water produced by extracting hydrogen from leftover rocket fuel, and potatoes intended for Thanksgiving dinner. He also begins to modify the only functional rover for longer journeys in preparation for the long distance travel.

Back on Earth, NASA holds a funeral for him. While reviewing satellite photos of Mars, satellite planner Mindy Park sees evidence of Watney's activities and realizes he has survived. NASA administrator Teddy Sanders has public relations director Annie Montrose and mission director Vincent Kapoor release the news. Despite the objections of Hermes flight director Mitch Henderson, Sanders decides not to inform the Ares III crew, believing it would distract them.

Watney takes the rover to retrieve the nearby Pathfinder probe, which fell silent in 1997. Using the lander's camera, he establishes rudimentary communication with Earth, first with plastic bin lids, and then using hexadecimals. NASA instructs Watney to partially modify the rover's code to link with Pathfinder so they can communicate via text. Watney becomes angry when he learns that the crew has not been told of his survival (and openly expresses it), and Sanders reluctantly lets Henderson finally inform them.

Henderson and JPL director Bruce Ng prepare a space probe to deliver enough food to last Watney until Ares IV's arrival. When the Hab's airlock malfunctions due to a small puncture, it destroys Watney's crops. Sanders orders the team to speed up the supply mission with the Iris probe by skipping the safety inspections. However, an oversight causes the destabilization and subsequent explosion of the rocket 40 seconds after liftoff, causing Watney to think about his seemingly inevitable death.

The China National Space Administration offers NASA the Taiyang Shen, a classified booster rocket that can carry a payload to Mars. Meanwhile, JPL astrodynamicist Rich Purnell devises a trajectory to divert Hermes back to Mars for a rescue more than two years earlier, using the Chinese booster to resupply Hermes for an additional eighteen months. Sanders rejects the plan, refusing to risk the crew, but Henderson surreptitiously sends the details to Hermes. The crew, knowing that going against orders will likely end their careers as astronauts, unanimously vote for the plan, and NASA — powerless to stop them — resupplies Hermes as it uses Earth's gravity to slingshot back to Mars.

Watney begins the 90-sol journey to Schiaparelli and the pre-positioned Ares IV MAV. To rendezvous with Hermes, Watney removes many components from the MAV, including the nose cone, to lighten it, replacing it with a piece of the Hab's canvas. As the MAV fails to reach the required speed and altitude, Lewis is forced to use maneuvering thrusters to change course and explosive decompression of Hermes's internal atmosphere to reduce speed. When even that is not enough, Commander Lewis uses a Manned Maneuvering Unit, but still cannot reach Watney. Watney pierces the glove of his pressure suit and uses the escaping air to propel himself towards Lewis, effectively rescuing him after being alone for 560 Sols on Mars.

After returning to Earth, Watney becomes a survival instructor for astronaut candidates. Five years later, on the occasion of the Ares V mission launch, those involved in Watney's rescue have begun new lives.
"""
      Array.append(MoviesObject(Name: "The Martian", About: TheMartianAbout, Image: #imageLiteral(resourceName: "The Martian")))
    //
    let TheRevenantAbout = """
العائد (بالإنجليزية: The Revenant) هو فيلم ويسترن وإثارة أمريكي من إخراج أليخاندرو غونزاليز إيناريتو، تدور أحداثه في عام 1823 ومستوحاة من حياة صياد الفراء ساكن الحدود هيو غلاس. النص من كتابة مارك إل سميث وإيناريتو، ومقتبس جزئيا من رواية بنفس الاسم لمايكل بنك. الفيلم من بطولة ليوناردو دي كابريو وتوم هاردي وويل بولتر ودومينال غليسون.
عُرض الفيلم لأول مرة في المسرح الصيني TLC في لوس أنجلوس 16 ديسمبر، 2015 وصدر بشكل محدود في 25 ديسمبر، 2015 ثم تبعه الإصدار الواسع في 8 يناير، 2016. تلقى الفيلم مراجعات إيجابية من النقاد، وبالأخص أداء دي كابريو وهاردي وإخراج إيناريتو وتصوير لوبزكي. ترشح الفيلم لـ 12 جائزة الأوسكار، فاز بثلاثة منها هي: أفضل تصوير سينمائي للوبزكي، وأفضل مخرج لأليخاندرو، وأفضل ممثل لليوناردو دي كابريو[10

القصة
تدور أحداث الفيلم عام 1823 حول صائد جلود الحيوانات هيو غلاس (دي كابريو) الذي يتعرض لهجوم من قِبل دب رمادي خلال هروبه هو ورفاقه من مطاردة قبيلة هندية. يقوم أحد رفاقه بنهبه وقتل ابنه وتركه ليموت وحيدا في الغابة، إلا أنه ينجو ويمضي في رحلة طولها 320 كم للانتقام من الرجل الذين خانه (هاردي) وقتل إبنه.

الممثلون والشخصيات
ليوناردو دي كابريو بدور هيو غلاس
توم هاردي بدور جون فيتزجيرالد
دومينال غليسون بدور الكابتن أندرو هنري
ويل بولتر بدور جيم بريدجير
فوريست غودلاك بدور هوك، ابن هيو غلاس
لوكاس هاس بدور جونز
براد كارتر بدور جوني

الاستقبال النقدي
تلقى الفيلم مراجعات إيجابية من النقاد، حيث حصل على تقييم 81% على موقع الطماطم الفاسدة بناءً على 193 مراجعة نقدية، مع متوسط تقييم 7.9/10، حيث كان الإجماع النقدي للموقع: "بجماله الصارخ وبقسوته الشديدة، يستخدم العائد أداء دي كابريو المتفاني كوُقود لهذه الدراما المُشوقة التي تُقدم تحديات صعبة - وثِمار غنية".[11] على موقع ميتاكريتيك حصل الفيلم على تقييم 77 من 100 بناءً على 48 مراجعة نقدية.

الميزانية والإيرادات
بلغت ميزانية الفيلم حوالي 135 مليون دولار، في حين بلغت إيراداته في افتتاحيته في صالات قرابة الأربعين مليون دولار، وبلغت إيراداته المحلية حتى الآن أكثر من 183 مليون، فيما وصلت الإيرادت الإجمالية إلى 526,493,034 مليون دولار بعد قرابة خمسة أشهر من عرض الفيلم في جميع أنحاء العالم.
"""

    Array.append(MoviesObject(Name: "The Revenant", About: TheRevenantAbout, Image:#imageLiteral(resourceName: "The Revenant") ))

    let SecretSuperstarAbout = """
The story of Secret Superstar is set in the town of Vadodara (Baroda) in Gujarat, India. Insia Malik (Zaira Wasim), a 15-year-old Indian Muslim girl, lives with her mother Najma (Meher Vij), younger brother Guddu, and an overbearing father Farookh (Raj Arjun). Insia is very passionate about singing, but her father is against her dream of becoming a singer.

Farookh goes out of town for work, and returns only once a week. Insia wants to participate in a music contest, which has a laptop and one free year of internet as a prize. Her mother tells her to get the permission of her father, but Insia never gets the chance as her father is busy scolding her and her mother. To satisfy her, Najma gifts Insia a laptop. Delighted with her present, Insia spends all her time on the laptop. She soon discovers that people have been using YouTube as a platform to record and post their songs. Insia records a song while disguising herself in a niqab, so Farookh can't find out her identity, and uploads the video on YouTube under the name of 'Secret Superstar'. She becomes an overnight sensation and grabs the attention of Shakti Kumar (Aamir Khan), who is a talented but rude music director and was a once successful singer. Shakti Kumar requests Insia to come to Mumbai for recording a song, but Insia refuses as she has heard a lot negative reviews of Shakti.

One day, Insia sees her tuition teacher's husband read an article about the Secret Superstar in the newspaper. Scared that her father will read the article too, she leaves the test to run home and hide the newspaper. Chintan, who has a crush on Insia, follows her, and tells her that he knows she is the 'Secret Superstar', recognizing her voice. Later he also proposes her in reply Insia with a blushing smile on her face ask him to leave.As she had left her test, Insia got very poor marks. Enraged, Farookh breaks her guitar.

Farookh is about to take Najma to a party and asks her to wear a necklace, when Najma starts making excuses. Realizing that Najma has sold it to buy the laptop, Insia takes her mother to another room to talk to her, but her father overhears them both. Furious, Farookh beats his wife and asks her to throw away the laptop. In a fit of rage, Insia herself throws away the laptop form the balcony and breaks down in her mother's arms. After seeing a famous lawyer on TV who fought against Shakti Kumar and won, Insia decides to approach her to get advice on divorce. With no other choice left, Insia accepts Shakti Kumar's proposal and goes to Mumbai, escaping school with help from Chintan. While escaping Chintan helps Insia jump out of school wall, after she is out she reveals that she too loves him [ Chintan ]and then leaves .

In Mumbai, Insia is initially unable to sing the party song, as she feels that the lyrics and the beats do not match. She tells Shakti that the song feels like a remix of another song which is never made, and Shakti tells her it's true. He sings the song as he original wrote it, and Insia realises what a good singer Shakti really is. Shakti tells her that the song is too slow for the generation today, as they all want fast-paced party songs. Insia asks Shakti to give the original song a try, and when she sings it, everyone is surprised and moved. The song is then recorded. The secret superstar's fame increases with the song and she is nominated for an award of best female singer.

Insia requests Shakti to fix a meeting with her and the lawyer. Reluctantly, Shakti fixes a date the following week. Insia meets the lawyer, who gives her some advice and files for signatures. Once home, her mother scolds her for going to Mumbai without informing anyone. She tells her she can't divorce Farookh as they would have no financial support otherwise. Angry at her mother's refusal, Insia throws a tantrum, but her grandmother reveals how Farookh had wanted to kill her before she was born, and how Najma has struggled to keep Insia alive. Farookh soon reveals that he has got a job in Saudi Arabia, which relieves Insia, as she would have to endure her father only a month a year, but her happiness is short-lived as Farookh tells her that he has fixed Insia's marriage to a Saudi boy and will take his entire family there. He buys tickets for Saudi in order to leave on the day Insia's final examination is over. Chintan and Shakti try to convince Insia to stay, but learning of her mother's efforts to keep her alive, Insia tells them she has no choice.

On the final day of school, Insia and Chintan spend their last joyful moments together. Chintan reveals that he is going for the award ceremony, and is going to cheer when Secret Superstar wins, but feels dejected that Insia won't come. Insia and her family leave for Saudi Arabia. At the airport's baggage counter, the clerk tells Farookh that they have one extra bag. Farookh scolds Najma for carrying the guitar and tells Insia to throw it away. For the first time, Najma protests against Farookh as she sees Insia break down in tears. When Farookh threatens to slap her in front of everybody, Najma signs the divorce papers, hands them to Farookh and marches out of the airport. She tells Insia to call Shakti so that they can arrive at the award ceremony. Shakti and Chintan are delighted to see Insia, who is still hiding her identity.

Unforutunately, Secret Superstar does not win the award. But the winner, Monali Thakur, says that she feels she does not deserve the award because she believes that Secret Superstar is a better singer than her and invites her to come to the stage and take the award. Insia reveals her identity on live television, and dedicates her award to Najma.

"""
    Array.append(MoviesObject(Name: "  Secret Superstar", About: SecretSuperstarAbout, Image: #imageLiteral(resourceName: "Secret Superstar") ))
    
    let RaeesAbout = """
رئيس (بالإنجليزية: Raees) هو فيلم جريمة هندي تم عرضه في 25 يناير 2017، من إخراج راهول دولاكيا وإنتاج كل من شركة فرحان أختر ريتيش سيدواني وشركة إكسل انترتينمنت والمنتجة غوري خان بشركة ريد تشيليز انترتينمنت. وهو من بطولة النجم شاه روخ خان و نواز الدين صديقي وماهيرا خان.
القصة
تدور أحداث القصة في الثمانينات في ولاية جوجارت الهندية، حيث تتسع تجارة المهرب رايس (شاروخان) من الكحول بدرجة كبيرة للغاية، ولكنه مع اتساع تجارته اتسعت دائرة رصده أيضًا، يتتبع أحد ضابط شرطة الشريف ذلك المهرب ويطارده بهدف القبض عليه لمنع تلك الأعمال غير المشروعة. وبعد ذالك ينتهي به المطاف بقتله من طرف ضابط الشرطة بسبب توريطه في جريمة صديقه و هي تفجير مدينة بأكملها و بسبب ضميره (رئيس) سلم نفسهبدون تردد•

"""
    Array.append(MoviesObject(Name: "Raees", About: RaeesAbout, Image: #imageLiteral(resourceName: "Raees") ))
    
    let NextAbout = """
Cris Johnson (Nicolas Cage) can see into his future. He can only see two minutes ahead, with the exception of a vision he once had of a woman walking into a diner. Knowing no details other than the time, he goes to the diner twice each day at 8:09 to await her arrival. He works as a small-time magician in Las Vegas, where he supplements his income with gambling, using his powers to win against the house.

Cris draws the attention of FBI agent Callie Ferris (Julianne Moore), who has figured out his ability and wants to stop Russian terrorists from detonating a nuclear weapon. Before she can approach Cris, his gambling draws the attention of casino security. He stops an imminent robbery, yet is chased by security agents. Using his ability to forecast the actions of his pursuers, he eludes them and the Las Vegas police. Ferris tracks Cris to his home, but he escapes after foreseeing her arrival. Later that night, the casino's security chief is approached by two of the terrorists, is interrogated about Johnson and is then killed.

The following morning, Cris is at the diner again when he sees Liz Cooper (Jessica Biel), the woman from his vision. It turns out that not only can Cris see the future, but he can also see how his actions can affect that future. After envisioning different approaches—all of which fall flat—he intervenes when Liz's ex-boyfriend arrives. Knowing that she is heading for Flagstaff, Arizona, Cris charms her into giving him a ride. Ferris follows, while the terrorists decide to kill him. A washed-out road forces Cris and Liz to spend the night in a motel. With the weapon tracked to Los Angeles, Ferris convinces her superiors to let her bring Cris in. The terrorists follow in the hope that the agents will lead them to Cris.

Ferris confronts Liz near the hotel. Claiming Cris is a dangerous sociopath, Ferris asks Liz to drug Cris so that they can bring him in peacefully. Instead, Liz warns Cris, who tells her his secret. When she asks why he will not help the FBI stop the terrorists, he explains his limitations, noting the exception for events involving her. Asking for Liz to wait for him, he tries to escape from the FBI agents but is captured after saving Ferris from logs tumbling down the side of a mountain. Unable to kill Cris, the terrorists kidnap Liz instead.

In custody, Cris is strapped to a chair with his eyes held open and forced to watch television until he has a vision that can help the FBI. They expect him to see a report about the detonation of the bomb, but instead he envisions a broadcast from several hours in the future in which Liz is killed by a small bomb while strapped to a wheelchair as bait for him. Cris escapes from captivity and races to the parking garage where she will be killed. Pursuing him to the garage, Ferris promises to help save her as long as Cris will help stop the bomb; she also sets up a plan to draw out the terrorists.

Using his ability, Cris helps the FBI track the terrorists to the port where they are based. When they arrive, Cris is able to walk right up to the terrorist leader and avoid being hit, by seeing where the bullets will go and dodging them. After killing the terrorists and saving Liz, they find that the bomb has already been moved. Ferris shows Cris a seismograph, hoping that he will see any tremors caused by explosions before they happen. As he stares at the screen he realizes that he has made a mistake and that he was too late: the bomb detonates out at sea and completely destroys the port, as well as the rest of the city.

The timeline reverts to Cris and Liz in bed at the hotel in Arizona, before Liz goes outside to be confronted by Ferris. Because of Liz's involvement in events, Cris has been able to envision everything that could happen leading to the nuclear explosion. "Every time you look into the future, it changes."

Cris calls Ferris and offers to help prevent the nuclear disaster, then asks Liz to wait for him.

"""
   Array.append(MoviesObject(Name: "Next", About: NextAbout, Image: #imageLiteral(resourceName: "Next") ))
    let DangalAbout = """
Mahavir Singh Phogat (Aamir Khan) is a former amateur wrestler and national champion based in Balali, a village in Haryana. He was forced by his father to give up the sport in order to obtain gainful employment. Dejected that he could not win a medal for his country, he vows that his unborn son will. Disappointed upon having four daughters, he gives up hope. But when his older daughters Geeta and Babita come home after beating up two boys in response to derogatory comments, he realises their potential to become wrestlers and begins coaching them.

His methods seem harsh, including grueling early morning workouts and short haircuts to avoid lice. Despite facing backlash from the villagers, he goes ahead with them, training them in his makeshift mud pit. Initially, the girls resent their father for his treatment but soon realise that he wants them to have a good future and not grow up to be stereotypical housewives. Motivated, they willingly participate in his coaching. Mahavir takes the girls to wrestling tournaments where they wrestle with boys and defeat them. Unable to afford wrestling mats, he uses two layers of mattresses and trains them in freestyle wrestling to prepare them for competitive events. Geeta goes on to win the junior and senior championships at the State and national level before heading to the National Sports Academy in Patiala to train for the forthcoming Commonwealth Games.

Once there, Geeta makes friends and begins to disregard the rigour and discipline she has been brought up with. She regularly watches television, eats street food, and grows her hair. Her coach's training methods and wrestling techniques differ significantly from her father's which she believes are superior. During a visit home, after taunting her father for his old techniques, she defeats her ageing and visibly exhausted father in a ferocious bout that ensues. Babita tells an unrepentant Geeta that she shouldn't forget their father's techniques and reminds her that she owes all the success to him. Winning the senior national championships herself, Babita follows Geeta to the academy. Geeta, however, finds herself losing every match at the international level. Subsequently, her coach coaxes her to compete in the 51 kg weight class from 55 kg. Frustrated, and persuaded by Babita, she tearfully makes peace with her father, who comes to Patiala with his nephew (Aparshakti Khurana) and begins coaching them secretly, using the same methods as when they were younger. Learning about this, and furious with Mahavir's interference, the coach wants the girls expelled. The sports authority allow them to continue and bar Mahavir from entering the academy and the girls to go out. Determined to continue assisting his daughters, Mahavir obtains tapes of Geeta's previous unsuccessful bouts and coaches her by pointing out her errors over the phone.

At the Games, competing in the 55 kg class, Geeta eases her way into the final. Mahavir constantly contradicts her coach's instructions while sitting in the audience which she follows while disregarding the latter. Just before the gold medal bout, the jealous coach conspires to lock Mahavir in a closet. Geeta lags behind managing to win the first session while losing the second. Trailing 1–5 in the final session and nine seconds left, she recalls the tactical techniques taught by her father and a 5-pointer that despite being difficult was not impossible. Geeta executes it on her opponent in the final three seconds, taking the score to 6–5 in her favour, thus winning the session, and the bout 2–1. In the process, she becomes the first Indian female wrestler to win gold at the Games. Mahavir returns just in time to embrace his daughters, frustrating the coach's hopes of obtaining credit before the news media.

"""
    Array.append(MoviesObject(Name: "Dangal", About: DangalAbout, Image: #imageLiteral(resourceName: "Dangal") ))
    
    let DontBreatheAbout = """
Rocky, Alex, and Money are three Detroit delinquents who make a living by breaking into homes secured by Alex's father's security company and selling the items they take. However, the person buying the stolen goods from Money doesn't give them a fair price, not enough to fund Rocky's dream of moving to California with her little sister, Diddy, to escape their abusive mother and her alcoholic boyfriend. Money receives a tip that a medically retired US Army Special Forces veteran living in an abandoned Detroit neighborhood has $300,000 in cash in his house, given as a settlement after a wealthy young woman, Cindy Roberts, killed his daughter in a car accident. The three stake out the house and discover that the man is in fact blind, as he was blinded from a blast during the Gulf War.

That night, the three approach the house and drug the Blind Man's dog. Finding all entrances locked, Rocky enters the house through a small window and lets the other two in. The group searches the house for the money but are unable to find it. Money puts a sleeping gas in the Blind Man's bedroom, then, assuming the money is behind a locked door downstairs, shoots the lock. The noise wakes up the Blind Man, who demands to know who else is with Money. Money insists he is alone, and the Blind Man kills him with his own gun. Terrified, Rocky hides in a closet, where she witnesses the Blind Man open a safe to check on his money. After he leaves, she opens the safe and takes the money, which appears to be at least $1 million. The Blind Man however finds Rocky's shoes and realizes that Money was not the only intruder.

Rocky and Alex evade the Blind Man and hurry to the basement. There, they are shocked to find a restrained, gagged woman in a homemade padded cell. Desperate, she shows them a newspaper article about the car accident; they realize that she is Cindy, the rich young woman, held captive by the Blind Man. They free her and run for the storm cellar door, only to be taken off guard by the Blind Man, who mistakenly shoots and kills Cindy. He breaks down crying when he discovers she is dead, sobbing "my baby." Rocky and Alex flee into the cellar while the Blind Man shuts off the lights, plunging them into darkness. After a blind struggle, Alex knocks out the Blind Man, and they flee upstairs.

After blocking the basement door, they encounter the Blind Man's Dog, who has woken. They're unable to unlock the front door in time before the dog attacks them, and are forced to flee into the bedroom, where they're trapped by the barred windows. Rocky escapes the room through a ventilation duct, while the dog attacks Alex, who falls out of a window onto a skylight, going unconscious. When Alex awakens, the Blind Man shoots out the skylight and corners Alex in his utility room, appearing to kill him with a pair of pruning shears. Meanwhile, the dog pursues Rocky through the vents, and she is captured by the Blind Man. She wakes up restrained in the basement like Cindy was, and the Blind Man reveals that Cindy was carrying his child in order to replace the one she killed. He then prepares to artificially inseminate Rocky with a turkey baster, explaining that she will now be the one to give him a child. It is revealed that the Blind Man accidentally stabbed Money's corpse with the shears instead of Alex, who manages to save Rocky and handcuff the Blind Man.

Rocky and Alex are unable to call the police, as their blood is all over the house, so they try to leave through the front door. The Blind Man breaks free and shoots Alex dead. Rocky flees, but is pursued by the dog. She manages to trap the dog in her car trunk, but is recaptured by the Blind Man. Inside his house, Rocky disorients the Blind Man by setting off his house's loud alarm system, then hits him repeatedly in the head with a crowbar and pushes him into the basement. The gun fires into his side as he falls. Believing him dead, Rocky escapes before the police arrive.

With the money, Rocky prepares to leave Detroit with Diddy on a train to Los Angeles. Before boarding, she sees a news report stating that the Blind Man killed two intruders (Alex and Money) in his house and is in stable condition at the hospital, but did not report Rocky or the stolen money.

"""
    Array.append(MoviesObject(Name: "Don't Breathe", About: DontBreatheAbout, Image: #imageLiteral(resourceName: "Don't Breathe") ))
    
    let LesMisérablesAbout = """
In 1815, French prisoner Jean Valjean is released on parole from the Bagne of Toulon after serving nineteen years for stealing a loaf of bread and trying to escape multiple times. On the outside, Valjean’s paroled status prevents him from getting work. He is offered shelter by the kindly Bishop of Digne, but Valjean steals his silverware. Captured by police and taken to the Bishop, Valjean is shocked when the Bishop says that he gave him the silver, telling him to use it to do something worthwhile with his life. Valjean breaks his parole to start a new life.

Eight years later, Valjean is factory owner and mayor of Montreuil, Pas-de-Calais. He is shocked when a Toulon prison guard Javert arrives as his new chief of police. Javert suspects Valjean’s identity when he rescues an injured worker trapped under a heavy cart. One of Valjean’s workers, Fantine, is dismissed by the factory foreman upon learning she is sending her earnings to her illegitimate daughter Cosette, who lives with the greedy innkeepers, the Thénardiers. To support her daughter, Fantine becomes a prostitute but is arrested by Javert when she attacks an abusive customer. Valjean, learning who she is, rescues her and takes her to the hospital.

Valjean learns a man has been wrongly identified as him, and reveals his true identity to a court before returning to the dying Fantine, promising to care for Cosette. Javert arrives but Valjean escapes, finding Cosette and pays Fantine’s debts to the Thénardiers. Valjean and Cosette flee Javert, hiding in a convent, aided by the worker Valjean rescued before. Nine years later, Valjean has become a philanthropist and helps the poor in Paris. General Lamarque, the only government official sympathetic to the poor, dies, and a group of revolutionists called the Friends of the ABC plot to rebel against the monarchy. Marius Pontmercy, a member of the Friends, encounters Cosette and they fall in love, asking Éponine, the Thénardiers’ daughter to help find her.

After Marius and Cosette meet and confess their love, Éponine prevents her father from robbing Valjean’s house. Valjean, believing Javert is near, makes plans to flee to England with Cosette. Cosette writes a letter for Marius, but Éponine hides it, intending on dying with Marius during the rebellion. During Lamarque’s funeral procession, the revolt begins and barricades are built across Paris. Javert pretends to be an ally to spy on the rebels but the street urchin Gavroche exposes him as a policeman. During the first skirmish against the soldiers, Éponine takes a bullet for Marius and dies in his arms, giving him Cosette’s letter and confesses to him beforehand. Gavroche takes Marius’ reply to Valjean, who joins the revolution to guard Marius.

Valjean offers to execute Javert but actually releases him, faking his death. By dawn, the soldiers are close to ending the revolution, storming the students’ barricade and execute everyone save Marius and Valjean, who escape into the sewers. Thénardier comes across Valjean and the unconscious Marius, stealing the latter’s ring, before pointing a way out. Valjean finds Javert waiting for him, ignoring his nemesis’ threats. Javert, morally confused by the mercy of Valjean, commits suicide by throwing himself in the Seine. Marius recovers but is traumatised by the death of his friends.

Marius and Cosette plan to marry but Valjean, concerned his presence would threaten their happiness, makes plans to leave and reveals his identity to Marius, who promises to remain silent. Cosette and Marius marry but the Thénardiers crash the wedding to try and blackmail Marius, Thénardier saying he witnessed Valjean carrying a murdered corpse and produces the stolen ring. Marius assaults Thénardier who reveals Valjean is at the convent. The dying Valjean reunites with Cosette and Marius, giving them letters of confession, before peacefully dying, guided away by Fantine and the Bishop’s spirits.

"""
    Array.append(MoviesObject(Name: " Les Misérables", About: LesMisérablesAbout, Image: #imageLiteral(resourceName: "Les Misérables") ))
    
    let MUDAbout = """
Two 14-year-old boys in the De Witt, Arkansas area, Ellis (Tye Sheridan) and Neckbone (Jacob Lofland), have found a boat stuck high in a tree on a small island in the Mississippi River. They want to claim it for themselves but discover someone is living in it. They meet him, a strange man named Mud (Matthew McConaughey), who claims to have grown up nearby. He tells the boys that he needs food and promises to give them the boat if they help him while he stays on the island.

The boys return with food and ask Mud why he is hiding out; he says he is waiting for his old girlfriend, Juniper (Reese Witherspoon), whom he describes as beautiful with bird tattoos on her hands. They later spot her grocery shopping in town. Ellis falls for an older high-school girl named May Pearl.

Ellis learns from his father that his parents are heading for divorce. This threatens their old river houseboat. Once no longer used as a residence by the owner, it will be removed.

Later, Ellis and his mother are stopped at a police roadblock. He then learns that Mud is a fugitive and tells the police that he has not seen that man. Ellis and Neckbone rush back to Mud and ask why the police are hunting him. Mud explains that he killed a man who had gotten Juniper pregnant and pushed her down a flight of stairs, causing her to lose the child. The boys decide to help Mud in exchange for his pistol.

Mud sends Ellis to Tom Blankenship (Sam Shepard), an older father figure from his childhood, for help. Tom lives across the river from Ellis and agrees to come talk to Mud but is disturbed to hear that Mud is in trouble over Juniper again and refuses to help.

After his plea for help is rejected by Tom, Mud gives the boys a note for Juniper. They find her motel room where another man (the brother of the man Mud killed) is abusing her. Ellis charges at the man but is quickly overpowered. Neckbone and Ellis tell Mud about the man. Mud realizes that the family of the man he killed has arrived to kill him.

King Carver (Joe Don Baker), the father of the man Mud murdered, and his surviving son (Paul Sparks) with a handful of bounty hunters talk about staking out Juniper's motel and have paid off the local and state police.

Stealing machine parts and an outboard motor from junkyards, the boys help Mud repair the boat. They also try to reunite Juniper with Mud, but she decides not to. Ellis suffers heartbreak when May Pearl rejects him in front of her friends.

Upon returning to the island, Ellis angrily calls Mud a liar, says he used the boys to do what he was afraid to do, and turned them into thieves. Running away, Ellis falls into a pit containing water moccasins and is bitten. Mud jumps in and rescues Ellis. Mud races to get the unconscious Ellis to hospital on the mainland. Recognizing Mud as the wanted man, one of the hospital employees calls the police who, in turn, tip off Carver.

Mud manages to get back to the island where he and Neckbone get the repaired boat into the water. As they agreed before, Mud gives Neckbone a Colt .45 semi-automatic pistol but without bullets. Mud wants to say good-bye to Ellis, so Neckbone takes him to the houseboat where he is recovering. While Mud is in Ellis' room, the Carver son and his posse arrive and start shooting. Tom fires his old sniper rifle, killing several attackers from across the river. Mud saves Ellis and tries to get away but is shot as he dives into the river. The police arrive and find all the posse members dead. One trooper calls King to tell him that his other son is now dead.

Ellis's parents separate. He and his mother move to an apartment in town and their houseboat is demolished, while his father gets a new job far away, before telling Ellis to take care of his mother and departs. Ellis sees some attractive older teenage girls there and smiles. He is uncertain of Mud's fate, but still believes he was protecting Juniper.

Mud is revealed to be alive and recovering on the repaired boat driven by Tom. Many days have passed, and the film ends with them looking ahead at the mouth of the Mississippi River, and south of that, the Gulf of Mexico.

"""
    Array.append(MoviesObject(Name: "MUD", About: MUDAbout, Image: #imageLiteral(resourceName: "MUD") ))
}
}
